-- V1__initial_schema.sql
-- Initial database schema for TaupHat Studio CMS

-- ── Site Configuration ─────────────────────────────────────────────────────────
CREATE TABLE site_config (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_name       VARCHAR(255) NOT NULL DEFAULT 'TaupHat',
    primary_color   VARCHAR(7)   NOT NULL DEFAULT '#5C4033',
    secondary_color VARCHAR(7)   NOT NULL DEFAULT '#D4A574',
    accent_color    VARCHAR(7)   NOT NULL DEFAULT '#8B6914',
    heading_font    VARCHAR(255) NOT NULL DEFAULT 'Playfair Display',
    body_font       VARCHAR(255) NOT NULL DEFAULT 'Open Sans',
    hero_image_url  VARCHAR(1024),
    about_text      TEXT,
    bigcartel_url   VARCHAR(1024),
    social_links    TEXT
);

-- Seed a default configuration row
INSERT INTO site_config (site_name) VALUES ('TaupHat');

-- ── Webcomic Series ────────────────────────────────────────────────────────────
CREATE TABLE webcomic_series (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(255) NOT NULL,
    slug            VARCHAR(255) NOT NULL UNIQUE,
    description     TEXT,
    cover_image_url VARCHAR(1024),
    sort_order      INT          NOT NULL DEFAULT 0,
    active          BOOLEAN      NOT NULL DEFAULT TRUE
);

-- ── Webcomic Issues ────────────────────────────────────────────────────────────
CREATE TABLE webcomic_issue (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_id       BIGINT       NOT NULL REFERENCES webcomic_series(id) ON DELETE CASCADE,
    issue_number    INT          NOT NULL,
    title           VARCHAR(255) NOT NULL,
    cover_image_url VARCHAR(1024),
    publish_date    DATE,
    published       BOOLEAN      NOT NULL DEFAULT FALSE,
    UNIQUE (series_id, issue_number)
);

-- ── Webcomic Pages ─────────────────────────────────────────────────────────────
CREATE TABLE webcomic_page (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id      BIGINT        NOT NULL REFERENCES webcomic_issue(id) ON DELETE CASCADE,
    page_number   INT           NOT NULL,
    image_url     VARCHAR(1024) NOT NULL,
    thumbnail_url VARCHAR(1024),
    optimized_url VARCHAR(1024),
    UNIQUE (issue_id, page_number)
);

-- ── Portfolio Items ────────────────────────────────────────────────────────────
CREATE TABLE portfolio_item (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(255)  NOT NULL,
    description   TEXT,
    image_url     VARCHAR(1024) NOT NULL,
    thumbnail_url VARCHAR(1024),
    optimized_url VARCHAR(1024),
    category      VARCHAR(255),
    sort_order    INT           NOT NULL DEFAULT 0
);

-- ── Indexes ────────────────────────────────────────────────────────────────────
CREATE INDEX idx_webcomic_issue_series ON webcomic_issue(series_id);
CREATE INDEX idx_webcomic_page_issue ON webcomic_page(issue_id);
CREATE INDEX idx_portfolio_item_category ON portfolio_item(category);
CREATE INDEX idx_portfolio_item_sort ON portfolio_item(sort_order);
