-- V3__add_portfolio_sets.sql
-- Add portfolio sets: ordered groupings of portfolio items with icon images.

CREATE TABLE portfolio_set (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               VARCHAR(255)  NOT NULL,
    description         TEXT,
    icon_image_url      VARCHAR(1024) NOT NULL,
    icon_thumbnail_url  VARCHAR(1024),
    icon_optimized_url  VARCHAR(1024),
    sort_order          INT           NOT NULL DEFAULT 0
);

ALTER TABLE portfolio_item ADD COLUMN set_id         BIGINT REFERENCES portfolio_set(id) ON DELETE SET NULL;
ALTER TABLE portfolio_item ADD COLUMN set_sort_order INT    NOT NULL DEFAULT 0;

CREATE INDEX idx_portfolio_item_set ON portfolio_item(set_id);
CREATE INDEX idx_portfolio_set_sort ON portfolio_set(sort_order);
