-- V8__add_commission_requests.sql
-- Commission requests drained from the Firestore "mail" queue and delivered by the CMS.

CREATE TABLE commission_request (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firestore_id  VARCHAR(255) NOT NULL UNIQUE,
    reply_to      VARCHAR(255),
    subject       VARCHAR(255),
    body          TEXT,
    status        VARCHAR(16)  NOT NULL,
    attempts      INT          NOT NULL DEFAULT 0,
    last_error    TEXT,
    received_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    sent_at       TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_commission_request_status ON commission_request(status);
CREATE INDEX idx_commission_request_received ON commission_request(received_at);
